function Format-Results {
  param(
    [hashtable]$results
  )

  try {
    $formattedResults = ($results.GetEnumerator() | ForEach-Object {
      "{0}: {1}" -f $_.Key, $_.Value
    }) -join "`n"
    return $formattedResults
  }
  catch [System.Collections.Generic.KeyNotFoundException] {
    Write-Error "Erro de chave nos resultados: $($_.Exception.Message)"
    return ""
  }
  catch [System.Management.Automation.RuntimeException] {
    Write-Error "Erro de tipo nos resultados: $($_.Exception.Message)"
    return ""
  }
}

# Exemplo de uso:
$resultados = @{
  Nome = "João";
  Idade = 30;
  Cidade = "São Paulo"
}

$textoFormatado = Format-Results -results $resultados
Write-Host $textoFormatado 
